name: GitHub Actions S3 website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download AWS CLI zip file
        run: sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        
      - name: Unzip AWS CLI zip
        run: sudo unzip awscliv2.zip
        
      - name: Installing AWS CLI
        run: sudo ./aws/install
